// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSQXsg6bTwFsPoTYiCfqGfm8Ptz1_lmrY',
    appId: '1:409489952952:web:ee557722849039b901644d',
    messagingSenderId: '409489952952',
    projectId: 'tomo-week-menu',
    authDomain: 'tomo-week-menu.firebaseapp.com',
    storageBucket: 'tomo-week-menu.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARawVyHOVl_IVMuhwD-zbxTaKOgesJXJk',
    appId: '1:409489952952:android:04a0a39697b5ff3401644d',
    messagingSenderId: '409489952952',
    projectId: 'tomo-week-menu',
    storageBucket: 'tomo-week-menu.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBt4ZHB_2anEqZSsxBTJmcb_Z5Srp4O0Y',
    appId: '1:409489952952:ios:97da4d4051621e3e01644d',
    messagingSenderId: '409489952952',
    projectId: 'tomo-week-menu',
    storageBucket: 'tomo-week-menu.appspot.com',
    iosClientId: '409489952952-p977kgjhdb5525n030vjtdl4v85ig3dm.apps.googleusercontent.com',
    iosBundleId: 'com.matteotomasini.menu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBt4ZHB_2anEqZSsxBTJmcb_Z5Srp4O0Y',
    appId: '1:409489952952:ios:1763b31429f883ac01644d',
    messagingSenderId: '409489952952',
    projectId: 'tomo-week-menu',
    storageBucket: 'tomo-week-menu.appspot.com',
    iosClientId: '409489952952-tlssmtq1u0o0aq2dcm8nqum6up1rpnd4.apps.googleusercontent.com',
    iosBundleId: 'com.matteotomasini.tomoweekmenu',
  );
}
